name: demo-secret
on:
  push:
    branches: [ actions1 ]
obs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
        run: |
          example-command "$super_secret"
          "$super_secret"