name: demo-secret
# This demo a secret3
on:
  push:
    branches: [ actions1 ]
    paths : 
      - 'secret/*'
jobs:
  - example-job:
      runs-on: ubuntu-latest
      steps:
        - name: Retrieve secret
          env:
            super_secret: ${{ secrets.SECRET_COMMAND }}
          run: |
            echo example-command "$super_secret"
            "$super_secret"
            pwd

  - secret-job:
      runs-on: ubuntu-latest
      steps:
        - name: Build
          run: echo "$SECRETCOMMAND"
          env:
            SECRETCOMMAND: ${{ secrets.SECRET_COMMAND }}